language: python
python: 3.6

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env: CM_CC=gcc-7 CM_CXX=g++-7 CM_BUILD_TYPE=Release

script:
  - cmake -H. -Bbuild -DCMAKE_C_COMPILER=${CM_CC} -DCMAKE_CXX_COMPILER=${CM_CXX} -DCMAKE_BUILD_TYPE=${CM_BUILD_TYPE}
  - cmake --build build
  - cd build && ctest -VV
