language: python
python:
  - '3.6'

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - libtool
            - autoconf
            - automake
            - pkg-config
            - g++-7
      env: LANG=en_US.UTF-8 CC=gcc-7 CXX=g++-7 BUILD_TYPE=Release

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && cmake --build . && ctest -VV 
