matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages:
            - gcc-7
            - g++-7
            - python3.6-dev
            - cmake
            - pkg-config
      env: CC=gcc-7 CXX=g++-7 BUILD_TYPE=Release

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. && cmake --build . && ctest -VV
