language: python
python: 3.6

matrix:
  include:
    - os: linux
      dist: xenial
      env: CC=gcc CXX=g++ BUILD_TYPE=Release

script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build build
  - cd build && ctest -VV
