language: python
python:
  - '3.6'

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # - cmake
            # - libtool
            # - autoconf
            # - automake
            # - pkg-config
            # - g++-7
      env: CC=gcc CXX=g++ BUILD_TYPE=Release
    - os: osx
      osx_image: xcode10.2
      env: CC=clang CXX=clang++ BUILD_TYPE=Release

script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build build
  - cd build && ctest -VV
