matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
          packages:
            - g++-4.9
            - python3.6-dev
            - cmake
      env: CC=gcc-4.9 CXX=g++-4.9 BUILD_TYPE=Release

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} .. && cmake --build . && ctest -VV
