image: ubuntu

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

test_script:
  - cd build && ctest -VV
