image: ubuntu

install:
  - ps: cd $APPVEYOR_BUILD_FOLDER && git submodule update --init --recursive

build_script:
  - ps: mkdir build
  - ps: cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build .

test_script:
  - ps: cd build && ctest -VV
